using Microsoft.EntityFrameworkCore;
using ProcessAnalyzer.Web.Models;

namespace ProcessAnalyzer.Web.Data;

// Every column name is spelled out with HasColumnName instead of relying on a naming-convention package:
// this schema is read by hand in psql and by phase-2 SQL that is not generated by EF, so the mapping has to
// be visible in one place and stable across EF upgrades rather than derived by a plugin.
//
// Every timestamp is timestamptz. No DateTime converter is installed and the Npgsql legacy timestamp switch
// stays off on purpose: Npgsql then throws when a DateTime with a non-UTC Kind reaches a timestamptz column.
// That throw is the guard. A converter that quietly "fixed" the Kind would shift business time by the local
// offset and we would only notice it as inexplicably reordered process traces months later.
public sealed class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options) { }

    public DbSet<JournalEvent> Events => Set<JournalEvent>();
    public DbSet<JournalEventObject> EventObjects => Set<JournalEventObject>();
    public DbSet<SyncCursor> Cursors => Set<SyncCursor>();
    public DbSet<SyncRun> Runs => Set<SyncRun>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        ConfigureJournalEvent(modelBuilder);
        ConfigureJournalEventObject(modelBuilder);
        ConfigureSync(modelBuilder);

        // Phase 2 attaches here: the ocel.* (object-centric event log) and analytics.* schemas are projected
        // from journal.* and get their own ConfigureOcel(modelBuilder) call. They are intentionally absent in
        // phase 1 — the mirror has to be proven correct before anything is derived from it.
    }

    private static void ConfigureJournalEvent(ModelBuilder modelBuilder)
    {
        var e = modelBuilder.Entity<JournalEvent>();
        e.ToTable("event", "journal");
        e.HasKey(x => x.SourceId);

        // The key is the source's id, not ours. Without ValueGeneratedNever EF treats an unset key as
        // "database will assign it", stops sending the column, and the mirror stops being a mirror: rows get
        // renumbered, the cursor points at ids that mean nothing in the source, and dedup by source id dies.
        e.Property(x => x.SourceId).HasColumnName("source_id").ValueGeneratedNever();

        e.Property(x => x.EventId).HasColumnName("event_id").IsRequired();
        e.Property(x => x.EventType).HasColumnName("event_type").IsRequired();
        e.Property(x => x.OccurredAt).HasColumnName("occurred_at").HasColumnType("timestamptz").IsRequired();
        e.Property(x => x.RecordedAt).HasColumnName("recorded_at").HasColumnType("timestamptz").IsRequired();

        e.Property(x => x.PerformerType).HasColumnName("performer_type").IsRequired();
        e.Property(x => x.PerformerId).HasColumnName("performer_id");
        e.Property(x => x.InitiatorType).HasColumnName("initiator_type");
        e.Property(x => x.InitiatorId).HasColumnName("initiator_id");

        e.Property(x => x.CorrelationId).HasColumnName("correlation_id");
        e.Property(x => x.TraceId).HasColumnName("trace_id");

        e.Property(x => x.SourceApplication).HasColumnName("source_application").IsRequired();
        e.Property(x => x.SourceModule).HasColumnName("source_module");
        e.Property(x => x.SourceVersion).HasColumnName("source_version");

        e.Property(x => x.Payload)
            .HasColumnName("payload")
            .HasColumnType("jsonb")
            .HasDefaultValueSql("'{}'::jsonb")
            .IsRequired();
        e.Property(x => x.PayloadRaw).HasColumnName("payload_raw");

        e.Property(x => x.MandateId).HasColumnName("mandate_id");
        e.Property(x => x.PulledAt)
            .HasColumnName("pulled_at")
            .HasColumnType("timestamptz")
            .HasDefaultValueSql("now()")
            .IsRequired();
        e.Property(x => x.ProjectionVersion).HasColumnName("projection_version").HasDefaultValue(0).IsRequired();

        // Unique on the source's own event id — the last line of defence against double-inserting an event
        // when a re-pull overlaps a range we already have.
        e.HasIndex(x => x.EventId).IsUnique().HasDatabaseName("ix_journal_event_event_id");

        e.HasIndex(x => new { x.EventType, x.OccurredAt }).HasDatabaseName("ix_journal_event_type_time");
        e.HasIndex(x => x.RecordedAt).HasDatabaseName("ix_journal_event_recorded");

        e.HasIndex(x => x.CorrelationId)
            .HasDatabaseName("ix_journal_event_corr")
            .HasFilter("\"correlation_id\" IS NOT NULL");

        // Work queue for the phase-2 projection: partial so it stays tiny once the backlog is drained,
        // instead of growing with the whole journal.
        e.HasIndex(x => x.SourceId)
            .HasDatabaseName("ix_journal_event_unproj")
            .HasFilter("\"projection_version\" = 0");
    }

    private static void ConfigureJournalEventObject(ModelBuilder modelBuilder)
    {
        var o = modelBuilder.Entity<JournalEventObject>();
        o.ToTable("event_object", "journal");
        o.HasKey(x => x.SourceId);

        // Same reasoning as JournalEvent.SourceId: mirrored key, never ours to generate.
        o.Property(x => x.SourceId).HasColumnName("source_id").ValueGeneratedNever();

        o.Property(x => x.EventSourceId).HasColumnName("event_source_id").IsRequired();
        o.Property(x => x.ObjectType).HasColumnName("object_type").IsRequired();
        o.Property(x => x.ObjectId).HasColumnName("object_id").IsRequired();
        o.Property(x => x.Qualifier).HasColumnName("qualifier").IsRequired();

        // No navigation property on either side (see JournalEventObject): the relationship exists so the
        // database enforces it and cascades deletes, not so EF can materialise graphs.
        o.HasOne<JournalEvent>()
            .WithMany()
            .HasForeignKey(x => x.EventSourceId)
            .HasPrincipalKey(x => x.SourceId)
            .OnDelete(DeleteBehavior.Cascade);

        // Natural key of a link. Makes re-reading an event's objects idempotent even if the source ever
        // renumbers the link rows themselves.
        o.HasIndex(x => new
            {
                x.EventSourceId,
                x.ObjectType,
                x.ObjectId,
                x.Qualifier,
            })
            .IsUnique()
            .HasDatabaseName("ux_journal_eo_natural");

        // "Everything that ever happened to this object" — the lookup the whole object-centric view rests on.
        o.HasIndex(x => new { x.ObjectType, x.ObjectId }).HasDatabaseName("ix_journal_eo_object");
        o.HasIndex(x => x.EventSourceId).HasDatabaseName("ix_journal_eo_event");
    }

    private static void ConfigureSync(ModelBuilder modelBuilder)
    {
        var c = modelBuilder.Entity<SyncCursor>();
        c.ToTable("cursor", "sync");
        c.HasKey(x => x.Name);
        c.Property(x => x.Name).HasColumnName("name");
        c.Property(x => x.Value).HasColumnName("value").IsRequired();
        c.Property(x => x.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamptz").IsRequired();

        var r = modelBuilder.Entity<SyncRun>();
        r.ToTable("run", "sync");
        r.HasKey(x => x.Id);

        // Unlike the journal keys, this id is ours: run rows have no counterpart in the source, so EF's
        // default generated identity is exactly right here.
        r.Property(x => x.Id).HasColumnName("id").ValueGeneratedOnAdd();

        r.Property(x => x.Kind).HasColumnName("kind").IsRequired();
        r.Property(x => x.StartedAt).HasColumnName("started_at").HasColumnType("timestamptz").IsRequired();
        r.Property(x => x.FinishedAt).HasColumnName("finished_at").HasColumnType("timestamptz");
        r.Property(x => x.FromId).HasColumnName("from_id");
        r.Property(x => x.ToId).HasColumnName("to_id");
        r.Property(x => x.Events).HasColumnName("events").HasDefaultValue(0).IsRequired();
        r.Property(x => x.Objects).HasColumnName("objects").HasDefaultValue(0).IsRequired();
        r.Property(x => x.HeldBack).HasColumnName("held_back").HasDefaultValue(0).IsRequired();
        r.Property(x => x.GapsFound).HasColumnName("gaps_found").HasDefaultValue(0).IsRequired();
        r.Property(x => x.ElapsedMs).HasColumnName("elapsed_ms");
        r.Property(x => x.Error).HasColumnName("error");
    }
}
