-- What somebody set up for themselves, which is the closest thing to a job description this system holds.
--
-- The log says who did what. It does not say who somebody IS. Many people work in the same module and do completely
-- different things with it, so every figure grouped by module is an average over roles that have nothing to do with
-- each other — and the group directory does not help, because a department is not a role: two dispatchers in the same
-- department differ in exactly the way that matters here.
--
-- Saved views answer it. Two people on the same screen keep different columns and narrow by different properties, and
-- that difference is the role: one works bound to a partner, another to a location, another to a vehicle. Nobody had to
-- be asked and nothing had to be instrumented — they configured it themselves, and the configuration is dated.
--
-- Deliberately STATE, not events. A screen being opened is not a fact — that decision stands, and it is why this lives
-- in dim.* beside the directory rather than in journal.*. Two thirds of the source journal is already one event type;
-- folding screen views into it would bury the facts for good.
--
-- Deliberately NAMES ONLY, no filter values. A filter value is free text a person typed — a customer name, a licence
-- plate, a vendor. The property NAME is a schema identifier and answers the role question on its own; the value would
-- import customer data into an analytical store for no analytical gain.

CREATE TABLE IF NOT EXISTS dim.saved_view (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id  bigint      NOT NULL UNIQUE,
    actor_key  text        NOT NULL,
    path       text        NOT NULL,
    name       text,
    is_default boolean     NOT NULL DEFAULT false,
    created_at timestamptz,
    changed_at timestamptz
);

COMMENT ON TABLE dim.saved_view IS
    'One view a person configured for themselves: which screen, when, and whether it is their default.';

-- The actor key, not the user id: the same pseudonym the projection uses, so a role can be joined to what somebody did
-- without a raw user id existing anywhere but dim.actor.
CREATE INDEX IF NOT EXISTS ix_saved_view_actor ON dim.saved_view (actor_key);
CREATE INDEX IF NOT EXISTS ix_saved_view_path ON dim.saved_view (path);

CREATE TABLE IF NOT EXISTS dim.saved_view_filter (
    view_id  bigint NOT NULL REFERENCES dim.saved_view (id) ON DELETE CASCADE,
    property text   NOT NULL,
    PRIMARY KEY (view_id, property)
);

COMMENT ON TABLE dim.saved_view_filter IS 'Which property a view narrows by. The name only — never the typed value.';

CREATE TABLE IF NOT EXISTS dim.saved_view_column (
    view_id  bigint  NOT NULL REFERENCES dim.saved_view (id) ON DELETE CASCADE,
    property text    NOT NULL,
    ord      integer NOT NULL,
    PRIMARY KEY (view_id, property)
);

COMMENT ON TABLE dim.saved_view_column IS 'Which columns a view keeps on screen, in their order.';

-- Which screens a person works on, and how deeply they set them up. Breadth is a role signal of its own: somebody with
-- views on one screen is a specialist, somebody with views on thirty is not.
CREATE OR REPLACE VIEW analytics.view_profile AS
SELECT v.actor_key,
       coalesce(i.display_name, 'unbekannt')       AS person,
       count(DISTINCT v.path)                      AS masken,
       count(*)                                    AS ansichten,
       count(DISTINCT f.property)                  AS filtermerkmale,
       max(v.changed_at)                           AS zuletzt_gepflegt
FROM dim.saved_view v
LEFT JOIN dim.actor i ON i.actor_key = v.actor_key
LEFT JOIN dim.saved_view_filter f ON f.view_id = v.id
GROUP BY v.actor_key, i.display_name
ORDER BY count(DISTINCT v.path) DESC, count(*) DESC;

-- The filter vocabulary: what people narrow their work by. Read as a list, this IS the role catalogue — each property
-- names a way of looking at the business, and the number of people using it says how many hold that role.
CREATE OR REPLACE VIEW analytics.filter_vocabulary AS
SELECT f.property,
       count(DISTINCT v.actor_key) AS personen,
       count(DISTINCT v.path)      AS masken,
       count(*)                    AS ansichten
FROM dim.saved_view_filter f
JOIN dim.saved_view v ON v.id = f.view_id
GROUP BY f.property
ORDER BY count(DISTINCT v.actor_key) DESC, count(*) DESC;

-- Who works on a screen, and what they look at there. The answer to "these eight people all use the order screen —
-- do they do the same thing?", which no module-level figure can give.
CREATE OR REPLACE VIEW analytics.view_population AS
SELECT v.path,
       count(DISTINCT v.actor_key)                                        AS personen,
       count(*)                                                           AS ansichten,
       count(DISTINCT f.property)                                         AS verschiedene_filter,
       (SELECT count(DISTINCT c.property) FROM dim.saved_view_column c
         JOIN dim.saved_view v2 ON v2.id = c.view_id AND v2.path = v.path) AS verschiedene_spalten
FROM dim.saved_view v
LEFT JOIN dim.saved_view_filter f ON f.view_id = v.id
GROUP BY v.path
ORDER BY count(DISTINCT v.actor_key) DESC;
