// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProcessAnalyzer.Web.Data;

#nullable disable

namespace ProcessAnalyzer.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProcessAnalyzer.Web.Models.JournalEvent", b =>
                {
                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("InitiatorId")
                        .HasColumnType("text")
                        .HasColumnName("initiator_id");

                    b.Property<string>("InitiatorType")
                        .HasColumnType("text")
                        .HasColumnName("initiator_type");

                    b.Property<long?>("MandateId")
                        .HasColumnType("bigint")
                        .HasColumnName("mandate_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("PayloadRaw")
                        .HasColumnType("text")
                        .HasColumnName("payload_raw");

                    b.Property<string>("PerformerId")
                        .HasColumnType("text")
                        .HasColumnName("performer_id");

                    b.Property<string>("PerformerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("performer_type");

                    b.Property<int>("ProjectionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("projection_version");

                    b.Property<DateTime>("PulledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasColumnName("pulled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("recorded_at");

                    b.Property<string>("SourceApplication")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_application");

                    b.Property<string>("SourceModule")
                        .HasColumnType("text")
                        .HasColumnName("source_module");

                    b.Property<string>("SourceVersion")
                        .HasColumnType("text")
                        .HasColumnName("source_version");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.HasKey("SourceId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_journal_event_corr")
                        .HasFilter("\"correlation_id\" IS NOT NULL");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_journal_event_event_id");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("ix_journal_event_recorded");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_journal_event_unproj")
                        .HasFilter("\"projection_version\" = 0");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("ix_journal_event_type_time");

                    b.ToTable("event", "journal");
                });

            modelBuilder.Entity("ProcessAnalyzer.Web.Models.JournalEventObject", b =>
                {
                    b.Property<long>("SourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("source_id");

                    b.Property<long>("EventSourceId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_source_id");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_id");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_type");

                    b.Property<string>("Qualifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qualifier");

                    b.HasKey("SourceId");

                    b.HasIndex("EventSourceId")
                        .HasDatabaseName("ix_journal_eo_event");

                    b.HasIndex("ObjectType", "ObjectId")
                        .HasDatabaseName("ix_journal_eo_object");

                    b.HasIndex("EventSourceId", "ObjectType", "ObjectId", "Qualifier")
                        .IsUnique()
                        .HasDatabaseName("ux_journal_eo_natural");

                    b.ToTable("event_object", "journal");
                });

            modelBuilder.Entity("ProcessAnalyzer.Web.Models.SyncCursor", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<long>("Value")
                        .HasColumnType("bigint")
                        .HasColumnName("value");

                    b.HasKey("Name");

                    b.ToTable("cursor", "sync");
                });

            modelBuilder.Entity("ProcessAnalyzer.Web.Models.SyncRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ElapsedMs")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_ms");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<int>("Events")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("events");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("finished_at");

                    b.Property<long?>("FromId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_id");

                    b.Property<int>("GapsFound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("gaps_found");

                    b.Property<int>("HeldBack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("held_back");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("Objects")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("objects");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<long?>("ToId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_id");

                    b.HasKey("Id");

                    b.ToTable("run", "sync");
                });

            modelBuilder.Entity("ProcessAnalyzer.Web.Models.JournalEventObject", b =>
                {
                    b.HasOne("ProcessAnalyzer.Web.Models.JournalEvent", null)
                        .WithMany()
                        .HasForeignKey("EventSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
