namespace ProcessAnalyzer.Web.Options;

public sealed class ProcessAnalyzerOptions
{
    public const string SectionName = "ProcessAnalyzer";
    public string SourceConnectionString { get; set; } = string.Empty;
    public int PullIntervalSeconds { get; set; } = 60;
    public int LagSeconds { get; set; } = 120;
    public int BatchSize { get; set; } = 5000;
    public int MaxPagesPerRun { get; set; } = 40;
    public int GapSweepDays { get; set; } = 3;
    public int GapSweepIntervalMinutes { get; set; } = 60;
    public bool AllowWriteCapableLogin { get; set; }

    /// <summary>
    /// Where a case can be opened in the system it came from, as object type to URL template with <c>{id}</c>.
    /// </summary>
    /// <remarks>
    /// The difference between a poster and a working tool: a reader who finds a case here wants to act on it, and that
    /// happens in the source system. Configuration rather than code, because the address of another system does not
    /// belong in this repository and every installation points somewhere else.
    /// <para>
    /// Read as JSON, for example <c>{"order":"https://erp.example/orders/{id}"}</c>. The id is the business key of the
    /// case, which is the part after the colon in an object id.
    /// </para>
    /// </remarks>
    public string? SourceLinks { get; set; }

    /// <summary>
    /// Key for the actor pseudonyms. Set once and keep it: rotating it changes every actor_key, which breaks the
    /// continuity of every handover statistic that was computed before the change.
    /// </summary>
    public string ActorHashKey { get; set; } = string.Empty;

    /// <summary>
    /// Whether the dashboard asks for a password. On by default: with names switched on, this tool shows who
    /// approves whose leave, and "only reachable inside the network" is not an access control.
    /// </summary>
    public bool RequireLogin { get; set; } = true;

    /// <summary>PBKDF2 hash of the dashboard password. Generated by the hash-password argument.</summary>
    public string DashboardPasswordHash { get; set; } = string.Empty;

    /// <summary>
    /// Whether screens show people by name or by pseudonym.
    /// </summary>
    /// <remarks>
    /// Off by default, because an installation that has not decided must not show names by accident. On, because
    /// "who approves whose leave" is a question an organisation is entitled to answer about itself, and a pseudonym
    /// cannot answer it. Either way the raw source id stays in dim.actor and no screen ranks people against
    /// each other — the switch changes what a person is called, not what is measured.
    /// </remarks>
    public bool ShowActorIdentity { get; set; }

    /// <summary>
    /// Which holiday calendar to use. Sources typically keep one per site; 0 picks the one with the most entries, which is
    /// the company-wide one in practice.
    /// </summary>
    public int HolidayCalendarId { get; set; }

    /// <summary>
    /// Which worktime model to use. Empty takes the median across all current models, because no single one speaks
    /// for everybody — and the screen says so rather than presenting a guess as a fact.
    /// </summary>
    public string WorktimeCalendarName { get; set; } = string.Empty;

    /// <summary>
    /// When a working day begins. The one piece of the calendar a source usually does not record — it keeps hours per
    /// weekday, not clock times — so it is configured here and stated on the screen rather than silently assumed.
    /// </summary>
    public string DayStartsAt { get; set; } = "07:00";

    /// <summary>Minutes between projection runs. The projection is local work over the mirror, so it can be frequent.</summary>
    public int ProjectionIntervalSeconds { get; set; } = 120;

    /// <summary>
    /// Directory holding the deployment's vocabulary: <c>labels.tsv</c>, <c>payload-allowlist.tsv</c> and the type
    /// catalogue. Read at startup, after the migrations.
    /// </summary>
    /// <remarks>
    /// Configuration, not code: which types a source declares and what each step is called differ per installation,
    /// so the tool ships the rules that render a label and takes the words from here. A wrong word is then corrected
    /// where it is used, without a release.
    /// </remarks>
    public string VocabularyPath { get; set; } = "vocabulary";
}
